<?php

use Illuminate\Database\Seeder;
use App\Container\gesap\src\Anteproyecto;
class AnteproyectosSeeder extends Seeder
{

    public function run()
    {
        Anteproyecto::insert([
            ['NPRY_Titulo'=> 'CONSTRUCCIÓN DE UN PROTOTIPO DE SOFTWARE PARA PROCESAR INFORMACIÓN DE POSICIÓN (X, Y, Z) DE UN CABALLO EN LA ESCUELA DE CARABINEROS "ALFONSO LÓPEZ PUMAREJO" CON EL FIN DE GENERAR MODELOS DE MOVIMIENTO\"','NPRY_Keywords'=> 'RNA, Acelerómetro, Xbee, FFT','NPRY_Duracion'=>6,'NPRY_FechaR'=>'2017-07-08','NPRY_FechaL'=>'2017-07-08','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'SOFTWARE DE GESTIÓN  DE SERVICIOS DEL CENTRO DE INVESTIGACIÓN Y TECNOLOGÍA DE LA UNIVERSIDAD DE CUNDINAMARCA EXTENSIÓN  FACATATIVÁ','NPRY_Keywords'=> 'Arquitectura de software, Software de servicios, Optimizacion de procesos,  Servidor de aplicaciones ','NPRY_Duracion'=>10,'NPRY_FechaR'=>'2017-07-11','NPRY_FechaL'=>'2017-07-12','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'Software para la obtención de datos laborales y seguimiento de graduados de la Universidad de Cundinamarca EXTENSIÓN FACATATIVÁ.','NPRY_Keywords'=> 'Web scraping, scrapers, minería de datos, raspado de datos, text mining, Graduados.','NPRY_Duracion'=>6,'NPRY_FechaR'=>'2017-07-12','NPRY_FechaL'=>'2017-07-20','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'PLATAFORMA WEB PARA LA GESTION DE ANTEPROYECTOS Y PROYECTOS DE GRADO PARA EL PROGRAMA INGENIERIA DE SISTEMAS EN LA UNIVERSIDAD DE CUNDINAMARCA, EXTENSIÓN FACATATIVÁ -"GESAP"','NPRY_Keywords'=> 'Gestión de Proyectos, Sitio Web, Estadistica, Investigacion Tecnologica, Innovacion de Procesos.','NPRY_Duracion'=>6,'NPRY_FechaR'=>'2017-07-23','NPRY_FechaL'=>'2017-07-27','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'APLICATIVO WEB PARA EL ANÁLISIS, SELECCIÓN Y ADMISIÁN DE ASPIRANTES AL PROGRAMA DE INGENIERÍA DE SISTEMAS DE LA UNIVERSIDAD DE CUNDINAMARCA EN LA EXTENSIÓN DE FACATATIVÁ UTILIZANDO MODELOS PREDICTIVOS','NPRY_Keywords'=> '_Datos, Mineria, desercion plataforma web, API REST_','NPRY_Duracion'=>6,'NPRY_FechaR'=>'2017-07-12','NPRY_FechaL'=>'2017-07-19','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'SISTEMA INFORMÁTICO PARA LA ASIGNACIÓN Y CONTROL DE LOS ESPACIOS ACADEMICOS EN LA UNIVERSIDAD DE CUNDINAMARCA EXTENSIÓN FACATATIVÁ','NPRY_Keywords'=> 'Espacios academicos, Laravel, Scrum, Sistematizar','NPRY_Duracion'=>6,'NPRY_FechaR'=>'2017-07-05','NPRY_FechaL'=>'2017-07-19','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'Modulo de implementacón de estándares de calidad en modelación y nomenclatura de base de datos','NPRY_Keywords'=> 'Evaluacion de modelacion de base de datos, estandares de calidad, Norma ISO/IEC/IEEE 25012, Norma ISO/IEC 19139,Nomenclatura.','NPRY_Duracion'=>12,'NPRY_FechaR'=>'2017-07-13','NPRY_FechaL'=>'2017-07-18','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'Modulo para la evaluación de estándares de codificación bajo la metodología de calidad de software para la universidad de cundinamarca','NPRY_Keywords'=> 'Calidad de software, Codificacion Deteccion de errores, Estandare de programacion, Evaluacion de proyectos','NPRY_Duracion'=>12,'NPRY_FechaR'=>'2017-07-27','NPRY_FechaL'=>'2017-07-27','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'DISEÑO, DESARROLLO E IMPLEMENTACIÓN DE  UN SISTEMA RFID PARA EL CONTROL DE INVENTARIO DE EQUIPOS TECNOLÓGICOS DE AUDIOVISUALES EN LA UNIVERSIDAD DE CUNDINAMARCA EXTENSIÓN FACATATIVÁ ','NPRY_Keywords'=> 'Audiovisuales, Inventario, Rfid, Software, Seguridad, Tecnologia','NPRY_Duracion'=>8,'NPRY_FechaR'=>'2017-07-12','NPRY_FechaL'=>'2017-07-20','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'MODULO FINANCIERO DEL SISTEMA DE INFORMACION PARA EL APOYO ADMINISTRATIVO UDEC-FACATATIVÁ- "SIAAF"','NPRY_Keywords'=> 'Software, tecnologica, metodologica, modulo financiero, seguridad.','NPRY_Duracion'=>12,'NPRY_FechaR'=>'2017-07-26','NPRY_FechaL'=>'2017-07-19','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'PLATAFORMA WEB PARA LA GESTIÓN Y CONTROL DEL RENDIMIENTO DEPORTIVO EN CLUBES DE FUTBOL: CASO DEPORTFUSA','NPRY_Keywords'=> 'Software, tecnologica, metodologias, futbol, rendimiento.','NPRY_Duracion'=>12,'NPRY_FechaR'=>'2017-07-27','NPRY_FechaL'=>'2017-07-18','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'DESARROLLO DE PROTOTIPO DE SISTEMA INTELIGENTE PARA REGISTRO E IDENTIFICACIÓN DE MARIPOSAS EN EL PARQUE METROPOLITANO MARIA LUCIA (VILLAVICENCIO) BASADO EN HMM Y RNA','NPRY_Keywords'=> 'Identificacion de imágenes, modelos ocultos de markov, reconocimiento de patrones, redes neuronales artificiales, sistemas inteligentes.','NPRY_Duracion'=>0,'NPRY_FechaR'=>'2017-07-19','NPRY_FechaL'=>'2017-07-25','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'CONSTRUCCIÓN DE UN PROTOTIPO DE SOFTWARE PARA EL REGISTRO Y CONTROL DE ACCESO INTELIGENTE DE MOTOCICLETAS AL PARQUEADERO DE LA UNIVERSIDAD DE CUNDINAMARCA EXTENSIÓN FACATATIVÁ','NPRY_Keywords'=> 'Control de acceso inteligente, Parqueadero, Reconocimiento de patrones, Redes neuronales artificiales (RNA).','NPRY_Duracion'=>6,'NPRY_FechaR'=>  '2017-07-18','NPRY_FechaL'=>'2017-07-18','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'SISTEMA DE RECOMENDACIÓN PARA VOCACIÓN PROFESIONAL, APLICADO A LA CARRERA DE INGENIERIA DE SISTEMAS OFRECIDA EN LA UNIVERSIDAD DE CUNDINAMARCA, EXTENSIÓN FACATATIVÁ','NPRY_Keywords'=> 'Sistemas de recomendación, Mineria de datos, Orientacion profesional, Clasificadores.','NPRY_Duracion'=>12,'NPRY_FechaR'=>'2017-07-18','NPRY_FechaL'=>'2017-07-19','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'IMPLEMENTACIÓN DE MÉTODOS DE TESTING NO HEURÍSTICO PARA LA EVALUACIÓN DE CALIDAD DE PRODUCTOS SOFTWARE','NPRY_Keywords'=> 'Automatizacion, ingenieria de la usabilidad, validacion, calidad, Testing, integracion de modulos','NPRY_Duracion'=>12,'NPRY_FechaR'=>'2017-07-26','NPRY_FechaL'=>'2017-07-25','NPRY_Estado'=>'EN ESPERA'],
['NPRY_Titulo'=> 'SISTEMA DE INFORMACION PARA EL APOYO ADMINISTRATIVO UDEC-FACATATIVÁ - "SIAAF", MODULO RECURSOS HUMANOS','NPRY_Keywords'=> 'Afiliaciones, Optimizacion de procesos, Plataforma web, Sistemas de informacion Talento humano','NPRY_Duracion'=>6,'NPRY_FechaR'=>'2017-07-22','NPRY_FechaL'=>'2017-07-12','NPRY_Estado'=>'EN ESPERA']

        ]);
        
    }
}