<?php

use App\Container\Gesap\src\Commits;
use \Illuminate\Database\Seeder;

class CommitGesapSeeder extends Seeder
{

    public function run()
    {
        Commits::insert([


            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'3',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'En la Universidad de Cundinamarca en el programa de Ingeniería de Sistemas extensión Facatativá actualmente existen dos versiones de la plataforma web para la Gestión de anteproyectos y proyectos de grado para el programa de Ingeniería de Sistemas en la Universidad de Cundinamarca extensión Facatativá - “GESAP”, esta plataforma consiste en un seguimiento y control a los grupos de estudiantes quienes estén haciendo el proceso de presentar anteproyecto y proyecto de grado. Los estudiantes que hayan sido aceptados como usuarios en la plataforma subirán inicialmente los archivos de MCTr008 y los Requerimientos IEEE de la idea de proyecto que se tenga. El predirector del grupo de estudiantes puede hacer un seguimiento desde la plataforma, con el fin de hacer más eficiente y eficaz el proceso. De la misma manera los docentes que sean habilitados con el rol de jurados o evaluadores de los proyectos, ingresan a la plataforma y evalúan los archivos del grupo asignado a calificar. Por otro lado, la plataforma tiene la posibilidad de mostrar graficas estadísticas de los anteproyectos y proyectos evaluados o finalizados, docentes con mejor promedio de proyectos finalizados, entre otros. 
            En base a lo anteriormente dicho, se propone una nueva versión de GESAP con el fin de corregir errores de la versión anteriormente descrita, modificar características y adicionando el hecho de que en la versión que se propone en este documento, como requerimiento, es hacer un estándar para la Universidad de Cundinamarca con el fin de que la plataforma quede aplicable principalmente al programa de ingeniería de sistemas de la extensión Facatativá, pero con la posibilidad de ser aplicable a los demás programas académicos de la universidad de Cundinamarca, de igual manera que pueda aplicarse en las demás sedes y extensiones de la misma entidad.
            '],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'4',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'Como apoyo a la actividad investigativa desarrollada en el programa de ingeniería de sistemas, extensión Facatativá, se crea con aval de Colciencias, en el año 2010 el grupo de investigación de sistemas y tecnología de Facatativá (GISTFA). Sobre el año 2012 GISTFA abandona el concepto de grupo de estudio con el que nació para dar paso a la creación de propuestas serias hacia la solución de problemas.
            Es así como GISTFA asume la responsabilidad de la investigación del programa con la tarea de convertir los resultados de sus semilleros en proyectos eficientes, óptimos y de impacto en la comunidad académica y en su entorno. Sobre esta base y bajo convenios hechos con las empresas de la región GISTFA ha implementado proyectos de desarrollo e innovación en la Alcaldía Municipal, Escuela de Comunicaciones, Policía Nacional y la empresa de aguas de Facatativá. Fue relevante para el grupo los trabajos desarrollados con el I.D.R.D del distrito Capital entre otras. Otros intereses de la investigación en el grupo GISTFA lo comprometen hacia una labor en la cual un ejercicio permanente actualice su razón de ser a partir de proyectos informáticos que generen conocimiento pertinente y consistente en el tiempo. Ahora bien, el grupo GISTFA crece y así las investigaciones orientadas por el grupo han contribuido a la creación de ambiciosas metas como la generación de proyectos interdisciplinarios (en el caso de la alianza con el grupo de investigación AXIOMA) y la transición hacia el emprendimiento y la innovación para fortalecer la transferencia de conocimiento y las conexiones con el sector empresarial. 
            Actualmente y desde su labor investigativa, el grupo GISTFA apoya al CIT (Centro de Innovación y Tecnologías) del programa de Ingeniería de Sistemas, Facatativá, con el objetivo de aumentar el impacto de los productos generados por el grupo de investigación GISTFA en la evaluación realizada por COLCIENCIAS y así mismo proponer nuevas metodologías de desarrollo como resultado de los productos generados a lo largo de la vida de los proyectos informáticos. En el año 2.017 y de acuerdo a los resultados del análisis para la medición de grupos de investigación en la Convocatoria 781 el grupo GISTFA fue reconocido y al participar en el proceso de medición de la Convocatoria en mención se obtuvo la categoría C. Actualmente la labor investigativa del grupo y su producción científica se orientan al logro de la categoría B en Colciencias.'],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'5',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'En la Universidad de Cundinamarca, extensión Facatativá, actualmente para el seguimiento y control de anteproyectos y proyectos de grado se ha manejado un estándar, a través del cual los estudiantes formulan y plantean la idea de proyecto y se presenta mediante documentos como el formato MCTr008 y un documento de Requerimientos IEEE, que hacen parte del anteproyecto, una vez se evalúa el anteproyecto y se determine el aval de los jurados asignados, la idea pasa a la realización (proyecto de grado) y en el camino del desarrollo se deben presentar otros documentos aparte de la finalización del proyecto, como son el libro y varios artículos de resultados. Por ende, el proceso de investigación descrito podría sintetizarse en el siguiente modelo (ver Gráfico 1).
            El objetivo de GESAP ha sido optimizar el tiempo que se lleva a cabo en el proceso anteriormente descrito, puesto que algunos ítems de este, llevan lapsos largos de investigación, particularmente el proceso de anteproyecto dividido en dos partes, MCTr008 y Requerimientos IEEE, es un ítem que puede durar todo un semestre, pues la investigación para presentar una idea de proyecto debe ser muy bien presentada al igual que los requerimientos deben estar debidamente desglosados con el fin de no atarearse al momento de hacer los modelados y el desarrollo del proyecto. Gesap en este momento se piensa como una plataforma en la que se pueda llevar un seguimiento y control más organizado, en donde los usuarios (directores, jurados y estudiantes) puedan ingresar y ver avances, dejar comentarios, calificar el anteproyecto en sus tres posibles estados (aprobado, aplazado, rechazado) y demás, pasos que actualmente se hacen en el proceso investigativo por parte de los estudiantes. Con respecto a los comentarios, se plantea el requerimiento con el fin de agilizar el proceso de visto bueno por parte del director del proyecto, ya que muchas veces no son posibles las reuniones entre estudiantes y director. Por las razones expuestas es que se hace necesario una plataforma web para la gestión del proceso investigativo llevado a cabo por los estudiantes, además de la posibilidad de poder implementar dicha plataforma en cada programa académico de la universidad de Cundinamarca.
            '],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'6',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'Actualmente en la Universidad de Cundinamarca extensión Facatativá y en el programa de ingeniería de sistemas, existen dos adaptaciones de GESAP; la última versión corresponde a una programación en lenguaje Laravel, dicha versión, aunque cumple con los objetivos y requerimientos, posee problemas en el manejo de bases de datos ya que no hay un control como tal del manejo de los datos, esto debido a que la información de usuarios, anteproyectos y proyectos se encuentra alojada en el código fuente de la plataforma y no posee comunicación alguna con un gestor de Base de Datos. Esta razón es la que no ha permitido el despliegue del aplicativo para el uso de directores, jurados y estudiantes de la plataforma web. 

            Por tanto es necesario hacer modificaciones a la versión uno (1) de GESAP con el objetivo de lograr el despliegue del aplicativo y poder hacer un seguimiento y control de anteproyectos y proyectos de grado en la universidad de Cundinamarca; se propone un mantenimiento al software y desarrollo de nuevas características para el aplicativo con el fin de implementarlo en todas las sedes y extensiones de la Universidad de Cundinamarca, no solo para el programa de Ingeniería de sistemas, sino para todos los programas que se encuentran avalados en la Universidad de Cundinamarca. 
            
            En conclusión a lo anteriormente dicho se plantea el siguiente cuestionamiento, ¿De qué manera se puede diseñar y desarrollar mejoras a la plataforma web para la gestión de proyectos y anteproyectos de grado del programa de ingeniería de sistemas de la universidad de Cundinamarca extensión Facatativá tal que mejore el proceso de revisión para que sea más eficiente, eficaz y optimice el tiempo de evaluación de los documentos que se radican para evaluación por parte de los jurados?
            '],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'7',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'Diseñar, modificar y desarrollar la plataforma web para la gestión de proyectos y anteproyectos de grado GESAP(V2) del programa de ingeniería de sistemas de la Universidad de Cundinamarca Extensión Facatativá, con el propósito de mejorar el proceso de revisión tal que sea más eficiente, eficaz y optimice el tiempo de evaluación de los documentos que se radican para evaluación por parte de los jurados.
            '],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'8',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'•	Levantamiento de nuevos requerimientos, basados en la versión inmediatamente anterior, adicionando la exigencia de que se adapte a los procedimientos actuales sobre gestión de proyectos de grado. •	Realización del modelo entidad relación (MER), además modelar bajo los parámetros UML.•	Construcción del agregado propuesto, requerido para la nueva versión de GESAP.•	Realizar las pruebas correspondientes al diseño y funcionamiento del sistema por medio de Calisoft.•	Determinar el Impacto social del proyecto por medio de Nvivo.'],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'9',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'Para el desarrollo de la plataforma se tomarán elementos de la metodología de desarrollo ágil Scrum para llevar a cabo en el presente proyecto, ya que permite tratarlo de manera más flexible y eficaz, hacer subdivisión del proyecto o dividirlo en tareas pequeñas. Esta metodología permite hacer cambios al que será el proyecto final, debido a que está sometido a alteraciones según se presenten avances, tal como lo explica Navarro (2013) en su documento sobre el análisis de las metodologías agiles: 
                Los proyectos ágiles se subdividen en proyectos más pequeños mediante una lista ordenada de características. Cada proyecto es tratado de manera independiente y desarrolla un subconjunto de características durante un periodo de tiempo corto, de entre dos y seis semanas. La comunicación con el cliente es constante al punto de requerir un representante de él durante el desarrollo. Los proyectos son altamente colaborativos y se adaptan mejor a los cambios; de hecho, el cambio en los requerimientos es una característica esperada y deseada, al igual que las entregas constantes al cliente y la retroalimentación por parte de él. (Navarro Cadavid, Fernández Martínez, & Morales Vélez, 2013).
                Entorno a lo descrito anteriormente, los elementos de la metodología ágil Scrum que se van a implementar para este proyecto y que fueron acordados con el director del mismo son:
                •	Reuniones semanales con el scrum master (directora del proyecto) y el equipo de desarrollo (estudiantes), en estas reuniones se deben presentar los avances realizados, correcciones de las observaciones de la ultima reunión y mostrar el progreso en el proyecto con ayuda de plataformas virtuales como Trello, que permite al grupo de desarrollo llevar un control de las tareas por hacer, que se están haciendo y que ya fueron finalizadas además de poder llevar el seguimiento por diferentes tableros según se requiera. 
                •	El scrum owner para este proyecto es el Centro de Innovación y Tecnología (CIT) (Equipo de desarrollo) de la universidad de Cundinamarca, extensión Facatativá, ya que es el propietario final del aplicativo. 
                •	El daily scrum no se vera implementado para este proyecto ya que es difícil por cuestiones de tiempo y ajuste de horario de parte del director y los estudiantes integrantes del proyecto. 
                •	El backlog que propone la metodología ágil Scrum para este proyecto se vera representado por el documento de Requerimientos IEEE debido a que son las exigencias propuestas a desarrollar. 
                Por otro lado, se aplicará la metodología ágil de desarrollo Extreme Programing XP (Programación extrema) que combinado junto a otras metodologías como lo es Scrum, el resultado final del producto es mejor y el lanzamiento a producción es más rápido debido a las iteraciones y pruebas que se llevan a cabo con el uso de esta metodología. 
                Para Joskowicz, 2014 “extreme Programming (XP) surge como una nueva manera de encarar proyectos de software, proponiendo una metodología basada esencialmente en la simplicidad y agilidad”. Por otro lado, para Bautista, 2012 “es una metodología ágil centrada en potenciar las relaciones interpersonales como clave para el éxito en desarrollo de software, promoviendo el trabajo en equipo, preocupándose por el aprendizaje de los desarrolladores, y propiciando un buen clima de trabajo”.
                ¿Qué es programación extrema o XP?
                •	Metodología liviana de desarrollo de software 
                •	 Conjunto de prácticas y reglas empleadas para desarrollar software
                •	Basada en diferentes ideas acerca de cómo enfrentar ambientes muy cambiantes 
                Objetivos:
                •	Establecer las mejores prácticas de Ingeniería de Software en los desarrollos de proyectos. 
                •	Mejorar la productividad de los proyectos. 
                •	Garantizar la Calidad del Software desarrollando, haciendo que este supere las expectativas del cliente.
                Característica Principal: 
                •	Basada en prueba y error (Bautista, 2012).
                Según lo anteriormente citado, para poder aplicar esta metodología en el grupo de desarrollo correspondiente al proyecto descrito hasta ahora, se es necesario de herramientas como GitHub y framework como GitKraken que permiten tener al día el código y trabajar en la versión más actualizada que se encuentre sin errores con el fin de desarrollar al tiempo sin crear conflictos y poder hacer pares de trabajo, que en otras palabras es probar lo que el compañero haya avanzado y viceversa; el poder mirar al tiempo el código agiliza la corrección de errores y hace más eficiente el proceso de desarrollo del código, garantiza que sea ordenado y que pueda llevarse a la producción rápidamente. 
                De la misma manera la metodología de investigación que se va a implementar y se llevara a cabo en este proyecto es la metodología mixta, está une la metodología cuantitativa y cualitativa, haciendo que se tomen lo mejor de ambas metodologías para así garantizar la realización de la idea inicial del proyecto. 
                Las investigaciones se originan de ideas, sin importar qué tipo de paradigma fundamente nuestro estudio ni el enfoque que habremos de seguir. Las ideas constituyen el primer acercamiento a la realidad objetiva (desde la perspectiva cuantitativa), a la realidad subjetiva (desde la aproximación cualitativa) o a la realidad intersubjetiva (desde la óptica mixta) que habrá de investigarse.(Baptista-lucio & Cómo, 2014)
                El enfoque cuantitativo utiliza la recolección y el análisis de datos para contestar preguntas de investigación y probar hipótesis establecidas previamente, y confía en la medición numérica, el conteo y frecuentemente en el uso de la estadística para establecer con exactitud patrones de comportamiento en una población. (Hernández-Sampieri, Fernández-Collado, & Baptista-Lucio, 2004).
                El enfoque cualitativo, por lo común, se utiliza primero para descubrir y refinar preguntas de investigación. A veces, pero no necesariamente, se prueban hipótesis. Con frecuencia se basa en métodos de recolección de datos sin medición numérica, como las descripciones y las observaciones. (Hernández-Sampieri et al., 2004).
                La metodología mixta ayudara a determinar el impacto social por medio de Nvivo, además de que en el futuro se realizaran encuestas que permitan establecer cuál fue la experiencia del usuario con el aplicativo para así llegar a estadísticas que comprueben si es funcional o no el uso de la plataforma web para la gestión de anteproyectos y proyectos de la universidad de Cundinamarca en el programa de ingeniería de sistemas extensión Facatativá – GESAP v2.
                En relación a la metodología mixta se propone una capacitación como mínimo a dos (2) anteproyectos y dos (2) proyectos de grado en el que se le explique al usuario el manejo del aplicativo web, posterior a la aplicación se deben emplear las encuestas ya mencionadas anteriormente que permitan determinar la usabilidad de la plataforma web además de hacer una breve entrevista con cada grupo de trabajo para que de la misma manera ayude a comprobar que el software sea fácil y sencillo de usar, que la interfaz sea amigable con los usuarios y que permita verificar que cumple con la optimización, eficiencia y eficacia del proceso de investigación del programa de ingeniería de sistemas de la universidad de Cundinamarca extensión Facatativá. Toda la información cualitativa será analizada por medio de la herramienta Nvivo que permite identificar el impacto social del proyecto. 
            '],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'20',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'Los trabajos de fin de estudios de una carrera universitaria son importantes para el estudiante y para la universidad, pues el estudiante depende de este trabajo para culminar sus estudios y poder graduarse; adicionalmente la universidad obtiene más reconocimiento pues por cada proyecto se genera producción científica (software, artículos que muestran resultados) que se registra ante Colciencias. Para ello se han propuesto formas de evaluación de proyectos, tal es el caso de la Escuela Superior Politécnica de la Universitat Pompeu Fabra, que hace uso de rúbricas para el seguimiento y evaluación de proyectos fin de carrera. Los primeros resultados muestran que de manera global, el uso de rúbricas permite sistematizar tanto el seguimiento como la evaluación de los trabajos realizados, a la vez que facilita la homogenización de criterios  (Moreno, Hernández Leo, Camps i Pujolar, & Melero Gallardo, 2012). 
            Antes de entrar en consideración del tema de evaluación y seguimiento de los proyectos fin de carrera, fin estudios, etc., se debe considerar la definición de proyecto, que según lo citado por EAFIT Universidad, Toro Cardona, Gomez Sanchez, & Pardo, (2015) es un esfuerzo temporal que se lleva a cabo para crear un producto, servicio o resultado único. La naturaleza temporal de los proyectos indica un principio y un final definidos. El final se alcanza cuando se logran los objetivos del proyecto o cuando se termina el proyecto porque sus objetivos no se cumplirán o no pueden ser cumplidos, o cuando ya no existe la necesidad que dio origen al proyecto. De la misma manera, los proyectos están adscritos a los grupos de investigación de la universidad, siendo financiados por la misma, pueden ser cofinanciados y(o) cooperados. (EAFIT Universidad et al., 2015). 
            Posterior a la definición de proyecto, se puede nombrar algunas características de este según (Moreno et al., 2012): 
            •	Es un trabajo de integración de las competencias adquiridas a lo largo de los estudios
            •	Se basa en la producción de un proyecto completo que se debe defender públicamente.
            •	El contenido de la asignatura es diferente para cada uno de los alumnos.
            •	La asignatura es –en gran medida- planificada y desarrollada por el alumno de forma autónoma.
            •	Se puede vincular al mundo empresarial.
            •	Implica una carga significativa de créditos, concretamente 20 ECTS en el caso de los estudios de ingeniería TIC de la ESUP.
            •	Requiere que el alumno demuestre un mayor nivel competencial que en las asignaturas trabajadas anteriormente, el cual debe equivaler a las expectativas correspondientes a los indicadores de Dublín para el primer ciclo.
            
            Sobre la base de la definición de proyecto y algunas características de este, se hace entonces la exposición de diferentes formas de llevar a cabo tanto el seguimiento como la evaluación de proyectos finales de grado. Se retoma el ejemplo de ESUP, que hace uso de rúbricas para seguimiento y evaluación de los proyectos; una rubrica en el contexto educativo se entiende como:
            un conjunto de criterios o de parámetros desde los cuales se juzga, valora, califica y conceptúa sobre un determinado aspecto del proceso educativo por lo que las rúbricas también pueden ser entendidas como pautas que permiten aunar criterios, niveles de logro y descriptores cuando de juzgar o evaluar un aspecto del proceso educativo se trata.(CUDI, 2010).
            Posterior a la definición de rúbrica en el área educativa, importante la definición del término para un mejor entendimiento de la idea a exponer citando como ejemplo a ESUP, que dice que: 
            las rúbricas diseñadas son tanto para el seguimiento del trabajo por parte del tutor como para la evaluación realizada por este último y el tribunal. Los criterios considerados para su elaboración fueron; a) las competencias a evaluar en cada caso (sistémicas e instrumentales), b) el agente que desempeñaba el rol de evaluador (tutor y tribunal) y c) los momentos definidos en la guía. Se realizaron las rúbricas considerando 4 posibles valores asociados al nivel de logro de cada caso, siendo 1 menor logro y 4 máximo logro, y que tenían por objetivo no sólo evaluar el producto final sino también el proceso, es decir, para facilitar el seguimiento del trabajo. (Moreno et al., 2012).
            Por otra parte, para este escrito es importante tener en cuenta el caso de INTEGRA, que expone: 
            La experiencia de INTEGRA ha demostrado la utilidad de disponer de un plan de evaluación permanente. Ello permitió realizar un seguimiento de los logros, así como detectar las dificultades que surgieron durante la implementación y poder así reorientar estrategias de trabajo y de acompañamiento de los docentes en las instituciones. Este plan deberá, además, ser flexible y periódicamente revisado para dar cabida a nuevas dimensiones y estrategias de evaluación. (Instituto Internacional de Planeamiento de Educación, 2007). 
            Los hallazgos que surgen de la evaluación y el seguimiento sirven para hacer ajustes a las actividades desarrolladas, intensificar algunas acciones, excluir otras. Sin una correcta evaluación y un adecuado seguimiento que dé cuenta de los logros parciales del proyecto y expliquen el porqué de algunas dificultades no es posible producir adecuaciones en el proyecto, lo que a su vez debilita la gestión de las acciones que lo conforman. Es por ello que la gestión y evaluación se encuentran íntimamente ligadas con el proceso de implementación de proyectos. (Instituto Internacional de Planeamiento de Educación, 2007). 
            Así mismo, el Instituto Internacional de Planeamiento de Educación ha definido que son los criterios de evaluación y el momento en que se aplican a un proyecto, “están dados por el conjunto de principios, metas o parámetros que sirven de punto de referencia y comparación para evaluar los resultados que surjan de su implementación. Estos criterios generalmente son definidos al comenzar el Plan de Evaluación” (Instituto Internacional de Planeamiento de Educación, 2007). 
            Más allá de los objetivos específicos de determinado proyecto, es conveniente considerar una serie de criterios “externos” vinculados con el avance de los procesos de incorporación de las TIC en las prácticas educativas y con los lineamientos de política educativa TIC existentes en la Autoridad Educativa. Algunos de estos pueden ser, por ejemplo, el nivel de competencias TIC de los docentes y estudiantes, el compromiso y las actitudes de los profesores hacia la utilización de tecnología, la infraestructura, equipamiento y recursos humanos disponibles en la institución, las posibilidades de capacitación y desarrollo profesional brindadas a los docentes. Estos se constituirán en algunos parámetros de referencia junto con los criterios específicos derivados del proyecto TIC institucional. (Instituto Internacional de Planeamiento de Educación, 2007).
            Con respecto al párrafo anterior, cabe resaltar que un objetivo de la evaluación de los proyectos es el uso de las TIC como medio para hacer el seguimiento de los proyectos finales de carrera, eso es lo que se propuso con GESAP (Plataforma Web para la gestión de proyectos y anteproyectos), una plataforma capaz de hacer el seguimiento a los trabajos finales de los estudiantes de ingeniería de sistemas en la universidad de Cundinamarca extensión Facatativá. Dicha plataforma se rige bajo el uso de TIC, ya que es una herramienta pensada en pro de los estudiantes y de los docentes tanto directores de proyecto como de los jurados o evaluadores de estos. 
            Los criterios que servirán de base para el seguimiento y evaluación del desarrollo y resultados de un proyecto TIC deberán atender, incorporar y operacionalizar:
            • los objetivos y criterios generales de evaluación fijados para los proyectos e iniciativas TIC que se desarrollen en el marco del sistema educativo de una gestión o autoridad educativa local;
            • los criterios y objetivos generales relativos al proyecto específico generado en una institución educativa en particular; y
            • los resultados intermedios y finales esperados para el conjunto del proyecto en caso de que la institución participe en algún tipo de programa o iniciativa más amplia en la cual incluya. (Instituto Internacional de Planeamiento de Educación, 2007).
            En este sentido se puede definir proyecto de ingeniería como: (Mas, Pascual, & Schönwälder, 2008) 
            Son proyectos cuyo resultado no acaba siendo tan solo una documentación, sino que es un resultado tangible, que acabará funcionando en la empresa y será utilizado por los usuarios. Acostumbran a ser aplicaciones informáticas, instalaciones de equipos o sistemas, la puesta en marcha de servicios. 
            En la misma fuente se definen unas fases para la metodología de proyectos informáticos que se sugiere aplicar: 
                La metodología propuesta consta de cinco fases: Antes del proyecto, Planificación del proyecto, Realización del proyecto, Documentación del proyecto y Después del proyecto.
                La fase de planificación del proyecto es considerada por todas las metodologías existentes y es clave para el éxito del proyecto. Lógicamente la ejecución del proyecto es vital, pero esto sí está en mente de todos los implicados. De todos modos, se tiende a pensar siempre en la ejecución, pero no en el seguimiento, ni tampoco en otros aspectos que mejoran la eficiencia. La documentación del proyecto es muy importante y debe empezarse a generar desde el primer momento. Es un error pensar que se puede realizar la documentación una vez finalizadas todas las tareas, pero es peor todavía pensar que ésta es prescindible. Una vez finalizado el proyecto, éste no se puede abandonar, ya que quedan pendientes todavía muchas actividades relacionadas que son importantes para que acabe con éxito. Algunas personas podrían considerar que, si el proyecto encuentra soluciones adecuadas y finaliza según el calendario previsto, ha finalizado con éxito. Nosotros pensamos que, para poder hablar de éxito, debe ser utilizado o continuado, en el caso que fuera necesario. (Mas et al., 2008).
                Parte de la investigación hecha incluyó el poder indagar acerca de las fases de un proyecto de fin de carrera, se establecen seis pasos o etapas para los Trabajos fin de estudios (TFE), los cuales constan de: 
                1. Definición de las competencias asociadas al TFG o al TFM y de sus indicadores objetivos;
                2. Definición de los momentos (hitos) de evaluación, de las acciones concretas de evaluación que deben realizarse en cada hito y de los agentes que llevarán a cabo la evaluación;
                3. Asignación de indicadores objetivos a cada una de las acciones de evaluación;
                4. Definición de los niveles de cumplimiento de cada indicador, estableciendo de forma clara y objetiva el nivel de competencia demostrado por el alumno en el indicador;
                5. Elaboración de los informes de evaluación que los agentes evaluadores deberán cumplimentar y
                6. Definición del criterio de puntación que asignará la nota final al TFE a partir de los resultados reflejados en los informes de evaluación. (Valderrama & Rullán, 2009).
                • Una primera evaluación que debe realizarse durante las primeras semanas, cuando el estudiante lleve trabajando en el TFE el tiempo necesario para haber desarrollado un planteamiento claro del trabajo a realizar, analizado el estado del tema propuesto, estudiado su viabilidad y organizado su plan de trabajo;
                • Uno (o varios) hitos de seguimiento a lo largo del proyecto, preferiblemente en la segunda mitad, donde se puedan detectar disfunciones en el planteamiento inicial y se esté a tiempo de realizar las correcciones necesarias y
                • Un hito de evaluación al finalizar el trabajo. 
                Finalmente, se proponen los agentes que deberán evaluar cada una de las acciones. Se considera que el director/tutor del trabajo debe estar presente en la evaluación de todas las acciones, aunque no necesariamente formar parte de los agentes evaluadores. (Valderrama & Rullán, 2009).
                Ahora bien, es relevante la consideración de los hitos para GESAP, ya que se dispone como requerimiento para la versión 3.0 de dicha plataforma, un nuevo proceso de evaluación, en el que el director y los jurados, tomados como agentes, sean quienes vayan calificando y dirigiendo a los estudiantes evaluados al éxito del proyecto, es decir, se quiere añadir a la plataforma, un apartado en donde los agentes mencionados sean capaces de hacer un comentario corrigiendo a los estudiantes, dándoles un plazo de corrección a estos. Por ello, resulta significativa la información sobre la evaluación de proyectos basándose en hitos o momentos.
                En relación al tema de los hitos y el seguimiento de proyectos, el autor Sanchez, Gonzalez, & Alayon, (2011), basándose en el modelo propuesto por Valderrama (2009), propone lo siguiente: 
                a) Definición de resultados de aprendizaje para el FYP y asignación de un conjunto de descriptores objetivos para cada uno. Del conjunto de 28 competencias sugeridas en el Tuning Proyect, hicieron una encuesta y obtuvieron 135 respuestas de Universidades, 107 de España y 28 del resto de Europa. Las cinco habilidades mejor calificadas fueron: 1) Poner en práctica los conocimientos adquiridos, 2) Habilidades de comunicación escrita y oral en su lengua materna, 3) Inicio, diseño e implementación de proyectos utilizando herramientas de ingeniería, 4) Organización y planificación, 5) Conocimiento sobre su campo de estudio.
                b) Definición de los hitos de la evaluación: quién y qué evaluará cada descriptor. Valderrama recomienda hacer una evaluación pronto en las primeras semanas del Proyecto para verificar que el estudiante haya analizado el estado del arte y que tenga una aproximación clara al mismo. Además, es necesario realizar varias evaluaciones a través del desarrollo del proyecto y una evaluación final al final.
                c) Asignación de descriptores a cada acción de evaluación. los descriptores asignados en ese caso fueron: 
                -Descriptor 1: el alumno presenta un diagrama de la planificación del proyecto.
                -Descriptor 2: El estudiante puede monitorear el nivel de cumplimiento con respecto al plan inicial y tener en cuenta las desviaciones del mismo.
                -Descriptor 3: el alumno analiza el nivel de cumplimiento con respecto al plan inicial, las causas de las desviaciones del plan original y sus consecuencias.
                d) Definición del nivel de cumplimiento para cada descriptor
                estableciendo un nivel de cumplimiento claro y objetivo para ser satisfecho por el estudiante. Los niveles de cumplimiento son: 0- El estudiante no cumple, 1 cumplimiento superficial, 2 cumplimiento adecuado, 3- Cumplimiento excelente
                e) Informe de evaluación. El informe de evaluación debe incluir descriptores, el nivel de cumplimiento y el nivel de demanda de cada descriptor. También proponen un informe general de evaluación organizado por habilidades.
                f) Calificación. La facultad o la universidad debe definir los criterios a seguir para proporcionar a los estudiantes las calificaciones. (Sanchez et al., 2011). 
                En relación al uso de rúbricas en los proyectos fin de carrera o fin de estudios según la bibliografía que se ha visto a lo largo de este estado del arte, Feldt, Höst, & Lüders, (2009) propone que:
                las universidades deben ser más claras sobre la importancia de las habilidades genéricas y definirlas y enseñarlas de forma más clara y durante todo el curso. En BTH, hemos desarrollado un marco basado en rúbricas para calificar tesis y proyectos de tesis. Ahora proponemos usar rúbricas también para definir y examinar habilidades genéricas en proyectos de tesis.
                A través de una prueba de Tuning, BTH comprueba que los estudiantes no desarrollan las habilidades necesarias o las mínimas competencias para llevar a cabo un proyecto de fin de carrera, no son capaces de resolverlo debido a falta de experiencias en diferentes campos, por medio de rubricas BTH propone el seguimiento para resolver dicha problemática en las universidades y sus estudiantes. 
                Creemos que un factor principal para explicar esto es que no está claro para los estudiantes qué significan diferentes competencias genéricas, como lo describe el proyecto Tuning. Proponemos que un marco de evaluación de tesis basado en rúbricas existente se puede extender para apoyar también la definición, aclaración y examen de habilidades genéricas.(Feldt et al., 2009). 
                Para terminar, es importante resaltar la importancia de un director, visto también como un líder, aquel que dirige y acompaña al grupo de estudiantes en el proceso de realización de los proyectos de fin de carrera o de estudios; en ingeniería el director de proyecto es aquel que está al tanto de los avances y guía al grupo al éxito del desarrollo del proyecto. 
                La responsabilidad del director del proyecto es la base de Gestión de proyectos. El gerente de proyecto como un director general, omni competente y de proceso completo, debe pensar en factores de influencia tales como factores ambientales y condiciones de restricción, etc. El gerente de proyecto debe adoptar una conducta altamente eficiente en ambos procesos de administración complicados. (Yu, Liu, & Fu, 2009).
                El gerente de proyecto, como director general, omni competente y de todo el proceso, desempeña un papel clave en el cumplimiento de los objetivos del proyecto. Cómo ejecutar la gestión del conocimiento, acumular sistemáticamente, generar y refinar las experiencias de cada gerente de proyecto con el fin de promover la difusión y el intercambio de conocimiento invisible es muy importante. (Yu et al., 2009).

                En relación a lo dicho hasta ahora en la descripción 8: el Estado del Arte, se propone un cuadro comparativo entre la última versión desarrollada de GESAP con la versión expuesta en este documento apoyándose en los requerimientos.
            '],

            ['FK_NPRY_IdMctr008'=>'3',
            'FK_MCT_IdMctr008'=>'11',
            'FK_User_Codigo'=>'123456189',
            'FK_CHK_Checklist'=>'2',
            'CMMT_Commit'=>'
            Baptista-lucio, C., & Cómo, P. (2014). Cómo se originan las investigaciones cuantitativas , cualitativas o mixtas, 24–29. Retrieved from http://metabase.uaem.mx/bitstream/handle/123456789/2771/506_2.pdf?sequence=1
            Bautista, J. (2012). PROGRAMACIÓN EXTREMA (XP) EXTREME PROGRAMMING (XP) ¿QUÉ ES PROGRAMACIÓN EXTREMA O XP? Retrieved from www.xprogramming.com/xpmag/whatisxp.htm.
            CUDI. (2010). Catalogo de rubricas para la evaluación del aprendizaje. Centro Universitario de Desarrollo Intelectual, 1–43. Retrieved from http://ponce.inter.edu/cai/reserva/lvera/RUBRICAS.pdf
            EAFIT Universidad, Toro Cardona, J. A., Gomez Sanchez, M., & Pardo, D. R. (2015). Dirección de investigación • universidad eafit.
            Feldt, R., Höst, M., & Lüders, F. (2009). Generic skills in Software Engineering Master thesis projects: Towards rubric-based evaluation. Proceedings - 22nd Conference on Software Engineering Education and Training, CSEET 2009, 12–15. https://doi.org/10.1109/CSEET.2009.54
            GISTFA. (2017). Grupo de Investigación de Sistemas Y Tecnologías de Facatativá.
            Hernández-Sampieri, R., Fernández-Collado, C., & Baptista-Lucio, P. (2004). Metodología de la Investigación. Retrieved from https://s3.amazonaws.com/academia.edu.documents/38911499/Sampieri.pdf?AWSAccessKeyId=AKIAIWOWYYGZ2Y53UL3A&Expires=1524083834&Signature=zIZyVwUpUOZCGz0r5qHl%2FQEvvmM%3D&response-content-disposition=inline%3B filename%3DSampieri.pdf
            Instituto Internacional de Planeamiento de Educación. (2007). Herramientas para la gestión de proyectos educativos con TIC. UNESCO, Sede Regional Buenos Aires, 1–93. Retrieved from http://unesdoc.unesco.org/images/0015/001580/158068s.pdf
            Joskowicz, J. (2014). Reglas y prácticas en eXtreme Programming. Universidad de Vigo. España, P8. https://doi.org/10.15381/idata.v13i2.6191
            Mas, R., Pascual, R., & Schönwälder, P. (2008). Nueva metodología de gestión de proyectos TIC para pymes ubicadas fuera de las áreas metropolitanas. II International Conference on …, (May), 293–304. Retrieved from http://www.adingor.es/congresos/web/articulo/detalle/a/226
            Moreno, V., Hernández Leo, D., Camps i Pujolar, I., & Melero Gallardo, J. (2012). Uso de rúbricas para el seguimiento y evaluación de los trabajos fin de grado, 1–12. Retrieved from https://repositori.upf.edu/bitstream/handle/10230/19801/erubricas_2012.pdf?sequence=1&isAllowed=y
            Navarro Cadavid, A., Fernández Martínez, J. D., & Morales Vélez, J. (2013). Revisión de metodologías ágiles para el desarrollo de software. Prospectiva (Vol. 11). https://doi.org/10.15665/rp.v11i2.36
            Sanchez, J. L., Gonzalez, C. S., & Alayon, S. (2011). Evaluation of transversal competences in the final year project in engineering. 2011 Proceedings of the 22nd EAEEIE Annual Conference (EAEEIE), 1–5.
            Valderrama, E., & Rullán, M. (2009). Guidelines for the final year project assessment in engineering. … , 2009. FIE’09. 39th …, 1–5. https://doi.org/10.1109/FIE.2009.5350767
            Yu, S., Liu, L., & Fu, M. (2009). The Application Research on Knowledge Management of Project Manager. 2009 International Conference on Information Management, Innovation Management and Industrial Engineering, 340–343. https://doi.org/10.1109/ICIII.2009.391
            
            '],
            
        ]);
    }
}
